source 'https://rubygems.org'

gem 'rails', '3.2.3'
gem 'sqlite3'

group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
end

group :test, :development do
  gem "rspec-rails", "~> 2.0"
  gem "capybara"
  gem "fabrication"
  gem 'rack-test'
end

group :production do
  gem "mysql2"
end

gem 'jquery-rails'
gem 'sorcery' 
gem 'hashie'
gem 'uniquify'
gem 'valid_email'
gem 'draper'
gem 'thin'
gem 'redis'
gem 'gravatar-ultimate'
gem 'speakeasy_on_tap', path: "../speakeasy_on_tap"
