source 'https://rubygems.org'

gem 'rails', '3.2.3'
gem 'redis'
gem 'mongoid'
gem 'bson_ext'
gem 'speakeasy_on_tap', path: "../speakeasy_on_tap"
gem 'jquery-rails'
gem 'highcharts-rails'

group :development, :test do
  gem 'rspec-rails'
  gem 'database_cleaner'
  gem 'capybara'
  gem 'factory_girl'
  gem 'guard'
  gem 'mongoid-rspec'
end

group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
end

